apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: fe5c5nqav-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fe5c5nqav-python 
  name: fe5c5nqav-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: fe5c5nqav-python 
